# Generated by Django 6.0.4 on 2026-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_increase_page_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pages_crawled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
