# Generated by Django 4.2.7 on 2026-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_llm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
