# Generated by Django 4.2.7 on 2026-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stop_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='llm_stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
